---
title: C26111 | Документация Майкрософт
ms.custom: ''
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
caps.latest.revision: 10
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: d6fa9c7ac56a96e7413e3b508e4ab581e5c3eef5
ms.sourcegitcommit: 9ceaf69568d61023868ced59108ae4dd46f720ab
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 10/12/2018
ms.locfileid: "49227819"
---
# <a name="c26111"></a>C26111
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Предупреждение C26111: вызывающей стороне не удается освободить блокировку \<блокировка > до вызова функции \<func >.  
  
 Заметка `_Requires_lock_not_held_` налагает предусловия, что счетчик блокировок для указанная блокировка не может быть больше нуля, при вызове функции. Предупреждение C26111 выдается при сбое функции для снятия блокировки, прежде чем он вызывает другую функцию.  
  
## <a name="example"></a>Пример  
 В следующем примере возникает предупреждение C26111, так как `_Requires_lock_not_held_` предусловие нарушено вызов `DoNotLock` в заблокированный раздел.  
  
```  
  
typedef struct _DATA   
{  
    CRITICAL_SECTION cs;  
    int d;  
} DATA;  
  
_Requires_lock_not_held_(p->cs)   
  
void DoNotLock(DATA* p)  
{  
    EnterCriticalSection(&p->cs);   
    p->d = 0;  
    LeaveCriticalSection(&p->cs);  
}  
  
void LockedFunction(DATA* p)   
{   
    EnterCriticalSection(&p->cs);   
    DoNotLock(p); // Warning C26111  
    LeaveCriticalSection(&p->cs);  
}  
  
```



