---
title: C28105
ms.date: 11/04/2016
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 455e06476d6841f468a64d45b350e45f3e8d1a75
ms.sourcegitcommit: 42ea834b446ac65c679fa1043f853bea5f1c9c95
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 04/19/2018
---
# <a name="c28105"></a>C28105
Предупреждение C28105: Утечка ресурса вследствие исключения

 Указанный ресурс не освобождается, когда возникает исключение. Инструкция, указанная в пути может вызвать исключение. Это предупреждение аналогично предупреждению [C28103](../code-quality/c28103.md), за исключением того, что в этом случае происходит исключение.

## <a name="example"></a>Пример
 Следующий пример кода вызывает появление этого предупреждения.

```
res = KeSaveFloatingPointState(buffer);

res = AllocateResource(Resource);
char *p2 = new char[10]; // could throw

delete[] p2;
FreeResource(Resource)
```

 Следующий пример кода позволяет избежать появления этого предупреждения.

```
res = AllocateResource(Resource);
char *p2;

try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
FreeResource(Resource)
```